import { pgTable, serial, varchar, text, timestamp, date, decimal, jsonb, integer, uniqueIndex, index } from 'drizzle-orm/pg-core';

export const approvalInstances = pgTable('approval_instances', {
  id: serial('id').primaryKey(),
  businessId: varchar('business_id', { length: 64 }).notNull(),
  title: varchar('title', { length: 500 }),
  processCode: varchar('process_code', { length: 64 }),
  processType: varchar('process_type', { length: 32 }),
  status: varchar('status', { length: 32 }),
  originatorUserId: varchar('originator_user_id', { length: 64 }),
  originatorDeptId: varchar('originator_dept_id', { length: 32 }),
  originatorDeptName: varchar('originator_dept_name', { length: 500 }),
  bizAction: varchar('biz_action', { length: 32 }).default('NONE'),
  createTime: timestamp('create_time', { mode: 'string' }),
  updateTime: timestamp('update_time', { mode: 'string' }).defaultNow(),
  cashierTaskId: varchar('cashier_task_id', { length: 64 }),
  cashierUserId: varchar('cashier_user_id', { length: 64 }),
  cashierStatus: varchar('cashier_status', { length: 32 }),
  cashierResult: varchar('cashier_result', { length: 32 }),
  cashierCompleteTime: timestamp('cashier_complete_time', { mode: 'string' }),
  flowResult: varchar('flow_result', { length: 32 }),
  department: varchar('department', { length: 128 }),
  applyType: varchar('apply_type', { length: 128 }),
  expenseType: varchar('expense_type', { length: 128 }),
  region: varchar('region', { length: 128 }),
  operationExpenseType: varchar('operation_expense_type', { length: 128 }),
  description: text('description'),
  beneficiary: varchar('beneficiary', { length: 500 }),
  amount: decimal('amount', { precision: 15, scale: 2 }),
  paymentTerms: varchar('payment_terms', { length: 128 }),
  currency: varchar('currency', { length: 32 }),
  baseCurrencyAmount: decimal('base_currency_amount', { precision: 15, scale: 2 }),
  paymentDate: date('payment_date', { mode: 'string' }),
  applyDate: date('apply_date', { mode: 'string' }),
  productionType: varchar('production_type', { length: 64 }),
  monthlyBudget: decimal('monthly_budget', { precision: 15, scale: 2 }),
  monthlyBudgetUsed: decimal('monthly_budget_used', { precision: 15, scale: 2 }),
  processInstanceId: varchar('process_instance_id', { length: 128 }),
  rawData: jsonb('raw_data'),
}, (table) => [
  uniqueIndex('uk_business_id').on(table.businessId),
  index('idx_approval_status').on(table.status),
  index('idx_cashier_status').on(table.cashierStatus),
  index('idx_create_time').on(table.createTime),
  index('idx_process_type').on(table.processType),
  index('idx_department').on(table.department),
]);
