import { pgTable, bigserial, varchar, decimal, text, timestamp, date, jsonb, uniqueIndex, index } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

export const approvalExpenseOperation = pgTable('approval_expense_operation', {
  id: bigserial('id', { mode: 'number' }).primaryKey(),
  processInstanceId: varchar('process_instance_id', { length: 128 }),
  businessId: varchar('business_id', { length: 64 }),
  requestDate: date('request_date', { mode: 'string' }),
  applicantDepartment: varchar('applicant_department', { length: 500 }),
  applicantDepartmentId: varchar('applicant_department_id', { length: 64 }),
  applicantDepartmentSource: varchar('applicant_department_source', { length: 32 }),
  applicantDepartmentPathIds: jsonb('applicant_department_path_ids'),
  applicantDepartmentPathNames: jsonb('applicant_department_path_names'),
  productionType: varchar('production_type', { length: 64 }),
  monthlyBudgetAmount: decimal('monthly_budget_amount', { precision: 18, scale: 2 }),
  monthlyBudgetUsedAmount: decimal('monthly_budget_used_amount', { precision: 18, scale: 2 }),
  monthlyBudgetRemainingAmount: decimal('monthly_budget_remaining_amount', { precision: 18, scale: 2 }),
  applicationType: varchar('application_type', { length: 128 }),
  expenseType: varchar('expense_type', { length: 128 }),
  executionRegion: varchar('execution_region', { length: 128 }),
  businessEntity: varchar('business_entity', { length: 64 }),
  serviceEntity: varchar('service_entity', { length: 64 }),
  formName: varchar('form_name', { length: 128 }),
  platform: varchar('platform', { length: 128 }),
  platformName: varchar('platform_name', { length: 255 }),
  storeName: varchar('store_name', { length: 255 }),
  operationExpense: varchar('operation_expense', { length: 128 }),
  employeeBenefitsExpense: varchar('employee_benefits_expense', { length: 128 }),
  bonusExpense: varchar('bonus_expense', { length: 128 }),
  salaryExpense: varchar('salary_expense', { length: 128 }),
  administrativeExpense: varchar('administrative_expense', { length: 128 }),
  vehicleUsageExpense: varchar('vehicle_usage_expense', { length: 128 }),
  taxExpense: varchar('tax_expense', { length: 128 }),
  financeRelatedExpense: varchar('finance_related_expense', { length: 128 }),
  salesExpense: varchar('sales_expense', { length: 128 }),
  salesChannelCommissionExpense: varchar('sales_channel_commission_expense', { length: 128 }),
  salesTeamCustomerServiceExpense: varchar('sales_team_customer_service_expense', { length: 128 }),
  otherSalesRelatedExpense: varchar('other_sales_related_expense', { length: 128 }),
  marketingAdvertisingExpense: varchar('marketing_advertising_expense', { length: 128 }),
  matterDescription: text('matter_description'),
  paymentDetailReason: text('payment_detail_reason'),
  beneficiary: varchar('beneficiary', { length: 500 }),
  amount: decimal('amount', { precision: 18, scale: 2 }),
  baseCurrencyAmount: decimal('base_currency_amount', { precision: 15, scale: 2 }),
  paymentTerms: varchar('payment_terms', { length: 255 }),
  currency: varchar('currency', { length: 32 }),
  paymentDate: date('payment_date', { mode: 'string' }),
  keyVoucher: text('key_voucher'),
  approvalCompletedAt: timestamp('approval_completed_at', { mode: 'string', withTimezone: true }),
  approvalStatus: varchar('approval_status', { length: 64 }),
  currentNode: varchar('current_node', { length: 255 }),
  currentOwner: varchar('current_owner', { length: 500 }),
  historicalApprovers: text('historical_approvers'),
  approvalNo: varchar('approval_no', { length: 128 }),
  creatorName: varchar('creator_name', { length: 255 }),
  sourceCreatedAt: timestamp('source_created_at', { mode: 'string', withTimezone: true }),
  sourceUpdatedAt: timestamp('source_updated_at', { mode: 'string', withTimezone: true }),
  creatorDepartment: varchar('creator_department', { length: 500 }),
  salaryByDepartment: jsonb('salary_by_department'),
  bonusByDepartment: jsonb('bonus_by_department'),
  officeEquipmentByDepartment: jsonb('office_equipment_by_department'),
  socialInsuranceByDepartment: jsonb('social_insurance_by_department'),
  officeSpaceByDepartment: jsonb('office_space_by_department'),
  individualIncomeTaxByDepartment: jsonb('individual_income_tax_by_department'),
  itOperationByDepartment: jsonb('it_operation_by_department'),
  rawData: jsonb('raw_data'),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true }).defaultNow(),
}, (table) => [
  uniqueIndex('uk_approval_expense_operation_business_id').on(table.businessId).where(sql`${table.businessId} IS NOT NULL`),
  uniqueIndex('uk_approval_expense_operation_process_instance_id').on(table.processInstanceId).where(sql`${table.processInstanceId} IS NOT NULL`),
  index('idx_approval_expense_operation_request_date').on(table.requestDate),
  index('idx_approval_expense_operation_department').on(table.applicantDepartment),
  index('idx_approval_expense_operation_applicant_department_id').on(table.applicantDepartmentId),
  index('idx_approval_expense_operation_status').on(table.approvalStatus),
  index('idx_approval_expense_operation_completed_at').on(table.approvalCompletedAt)
    .where(sql`${table.approvalCompletedAt} IS NOT NULL`),
]);
