import { pgTable, bigserial, varchar, decimal, text, timestamp, date, jsonb, uniqueIndex, index } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

export const approvalExpensePurchase = pgTable('approval_expense_purchase', {
  id: bigserial('id', { mode: 'number' }).primaryKey(),
  processInstanceId: varchar('process_instance_id', { length: 128 }),
  businessId: varchar('business_id', { length: 64 }),
  requestDate: date('request_date', { mode: 'string' }),
  applicantDepartment: varchar('applicant_department', { length: 500 }),
  applicantDepartmentId: varchar('applicant_department_id', { length: 64 }),
  applicantDepartmentSource: varchar('applicant_department_source', { length: 32 }),
  applicantDepartmentPathIds: jsonb('applicant_department_path_ids'),
  applicantDepartmentPathNames: jsonb('applicant_department_path_names'),
  productionType: varchar('production_type', { length: 64 }),
  monthlyBudgetAmount: decimal('monthly_budget_amount', { precision: 18, scale: 2 }),
  monthlyBudgetUsedAmount: decimal('monthly_budget_used_amount', { precision: 18, scale: 2 }),
  monthlyBudgetRemainingAmount: decimal('monthly_budget_remaining_amount', { precision: 18, scale: 2 }),
  businessEntity: varchar('business_entity', { length: 64 }),
  serviceEntity: varchar('service_entity', { length: 64 }),
  formName: varchar('form_name', { length: 128 }),
  purchaseExpense: varchar('purchase_expense', { length: 128 }),
  orderName: varchar('order_name', { length: 255 }),
  projectName: varchar('project_name', { length: 255 }),
  productName: varchar('product_name', { length: 255 }),
  ywOemImlPhoneCase: varchar('yw_oem_iml_phone_case', { length: 128 }),
  ywOemPhoneCase: varchar('yw_oem_phone_case', { length: 128 }),
  ywOemTabletCase: varchar('yw_oem_tablet_case', { length: 128 }),
  ywOemSupport: varchar('yw_oem_support', { length: 128 }),
  ywMoldesOdm: varchar('yw_moldes_odm', { length: 128 }),
  consultingServices: varchar('consulting_services', { length: 128 }),
  tiktokOnlineStore: varchar('tiktok_online_store', { length: 128 }),
  executionRegion: varchar('execution_region', { length: 128 }),
  orderPurchase: varchar('order_purchase', { length: 128 }),
  expenseClassification: varchar('expense_classification', { length: 255 }),
  investmentPurchase: varchar('investment_purchase', { length: 128 }),
  servicePurchase: varchar('service_purchase', { length: 128 }),
  mroClassification: varchar('mro_classification', { length: 128 }),
  productiveMro: varchar('productive_mro', { length: 128 }),
  nonProductiveMro: varchar('non_productive_mro', { length: 128 }),
  pdsClassification: varchar('pds_classification', { length: 128 }),
  pieceworkOutsourcing: varchar('piecework_outsourcing', { length: 128 }),
  logisticsTransportService: varchar('logistics_transport_service', { length: 128 }),
  customsClearanceService: varchar('customs_clearance_service', { length: 128 }),
  detailSummaryAmount: decimal('detail_summary_amount', { precision: 18, scale: 2 }),
  baseCurrencyAmount: decimal('base_currency_amount', { precision: 15, scale: 2 }),
  keyVoucher: text('key_voucher'),
  approvalCompletedAt: timestamp('approval_completed_at', { mode: 'string', withTimezone: true }),
  approvalStatus: varchar('approval_status', { length: 64 }),
  currentNode: varchar('current_node', { length: 255 }),
  currentOwner: varchar('current_owner', { length: 500 }),
  historicalApprovers: text('historical_approvers'),
  approvalNo: varchar('approval_no', { length: 128 }),
  creatorName: varchar('creator_name', { length: 255 }),
  sourceCreatedAt: timestamp('source_created_at', { mode: 'string', withTimezone: true }),
  sourceUpdatedAt: timestamp('source_updated_at', { mode: 'string', withTimezone: true }),
  creatorDepartment: varchar('creator_department', { length: 500 }),
  rawData: jsonb('raw_data'),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true }).defaultNow(),
}, (table) => [
  uniqueIndex('uk_approval_expense_purchase_business_id').on(table.businessId).where(sql`${table.businessId} IS NOT NULL`),
  uniqueIndex('uk_approval_expense_purchase_process_instance_id').on(table.processInstanceId).where(sql`${table.processInstanceId} IS NOT NULL`),
  index('idx_approval_expense_purchase_request_date').on(table.requestDate),
  index('idx_approval_expense_purchase_department').on(table.applicantDepartment),
  index('idx_approval_expense_purchase_applicant_department_id').on(table.applicantDepartmentId),
  index('idx_approval_expense_purchase_status').on(table.approvalStatus),
]);
